version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Docker image a
          command: docker build -t my-app .
